# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/TH/2026au/FPGA/The-World-Fastest-CNN-Using-FPGA/PE/PE.srcs/sources_1/ip/blk_mem_gen_wgt/blk_mem_gen_wgt.xci
# IP: The module: 'blk_mem_gen_wgt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TH/2026au/FPGA/The-World-Fastest-CNN-Using-FPGA/PE/PE.srcs/sources_1/ip/blk_mem_gen_wgt/blk_mem_gen_wgt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_wgt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/TH/2026au/FPGA/The-World-Fastest-CNN-Using-FPGA/PE/PE.srcs/sources_1/ip/blk_mem_gen_wgt/blk_mem_gen_wgt.xci
# IP: The module: 'blk_mem_gen_wgt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TH/2026au/FPGA/The-World-Fastest-CNN-Using-FPGA/PE/PE.srcs/sources_1/ip/blk_mem_gen_wgt/blk_mem_gen_wgt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_wgt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
