# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/TH/2026au/FPGA/The-World-Fastest-CNN-Using-FPGA/PE/PE.srcs/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
# IP: The module: 'xbip_dsp48_macro_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TH/2026au/FPGA/The-World-Fastest-CNN-Using-FPGA/PE/PE.srcs/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/TH/2026au/FPGA/The-World-Fastest-CNN-Using-FPGA/PE/PE.srcs/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
# IP: The module: 'xbip_dsp48_macro_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TH/2026au/FPGA/The-World-Fastest-CNN-Using-FPGA/PE/PE.srcs/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_dsp48_macro_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
