# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/TH/2026au/FPGA/DPU_new/DPU_new.srcs/sources_1/bd/ps_dpu/ip/ps_dpu_axi_gpio_0_2/ps_dpu_axi_gpio_0_2.xci
# IP: The module: 'ps_dpu_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TH/2026au/FPGA/DPU_new/DPU_new.srcs/sources_1/bd/ps_dpu/ip/ps_dpu_axi_gpio_0_2/ps_dpu_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dpu_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/TH/2026au/FPGA/DPU_new/DPU_new.srcs/sources_1/bd/ps_dpu/ip/ps_dpu_axi_gpio_0_2/ps_dpu_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dpu_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/TH/2026au/FPGA/DPU_new/DPU_new.srcs/sources_1/bd/ps_dpu/ip/ps_dpu_axi_gpio_0_2/ps_dpu_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dpu_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/TH/2026au/FPGA/DPU_new/DPU_new.srcs/sources_1/bd/ps_dpu/ip/ps_dpu_axi_gpio_0_2/ps_dpu_axi_gpio_0_2.xci
# IP: The module: 'ps_dpu_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TH/2026au/FPGA/DPU_new/DPU_new.srcs/sources_1/bd/ps_dpu/ip/ps_dpu_axi_gpio_0_2/ps_dpu_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dpu_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/TH/2026au/FPGA/DPU_new/DPU_new.srcs/sources_1/bd/ps_dpu/ip/ps_dpu_axi_gpio_0_2/ps_dpu_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dpu_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/TH/2026au/FPGA/DPU_new/DPU_new.srcs/sources_1/bd/ps_dpu/ip/ps_dpu_axi_gpio_0_2/ps_dpu_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_dpu_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
