# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ps_dpu/ps_dpu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu || ORIG_REF_NAME==ps_dpu} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_top_wrapper_0_0/ps_dpu_top_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_top_wrapper_0_0 || ORIG_REF_NAME==ps_dpu_top_wrapper_0_0} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_processing_system7_0_0/ps_dpu_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_processing_system7_0_0 || ORIG_REF_NAME==ps_dpu_processing_system7_0_0} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_rst_ps7_0_100M_0/ps_dpu_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_rst_ps7_0_100M_0 || ORIG_REF_NAME==ps_dpu_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_ps7_0_axi_periph_0/ps_dpu_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_ps7_0_axi_periph_0 || ORIG_REF_NAME==ps_dpu_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_xbar_0/ps_dpu_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_xbar_0 || ORIG_REF_NAME==ps_dpu_xbar_0} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_axi_gpio_0_2/ps_dpu_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_axi_gpio_0_2 || ORIG_REF_NAME==ps_dpu_axi_gpio_0_2} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_axi_bram_ctrl_0_1/ps_dpu_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_axi_bram_ctrl_0_1 || ORIG_REF_NAME==ps_dpu_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_axi_bram_ctrl_1_1/ps_dpu_axi_bram_ctrl_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_axi_bram_ctrl_1_1 || ORIG_REF_NAME==ps_dpu_axi_bram_ctrl_1_1} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_auto_ds_0/ps_dpu_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_auto_ds_0 || ORIG_REF_NAME==ps_dpu_auto_ds_0} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_auto_pc_0/ps_dpu_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_auto_pc_0 || ORIG_REF_NAME==ps_dpu_auto_pc_0} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_auto_pc_1/ps_dpu_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_auto_pc_1 || ORIG_REF_NAME==ps_dpu_auto_pc_1} -quiet] -quiet

# IP: bd/ps_dpu/ip/ps_dpu_auto_us_0/ps_dpu_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_dpu_auto_us_0 || ORIG_REF_NAME==ps_dpu_auto_us_0} -quiet] -quiet

# XDC: bd/ps_dpu/ps_dpu_ooc.xdc
